#!/bin/sh

#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -
# Usage: seatunnel-web {start|stop|status}
CONFDIR=${CONFDIR:-"/etc/seatunnel-web/conf"}

# Load environment variables if the configuration file exists
if [ -f "${CONFDIR}/seatunnel-web-env.sh" ]; then
    . "${CONFDIR}/seatunnel-web-env.sh"
else
    echo "Error: ${CONFDIR}/seatunnel-web-env.sh not found."
    exit 1
fi
if [ -z "${SEATUNNEL_WEB_HOME}" ]; then
    echo "Error: SEATUNNEL_WEB_HOME is not set. It must be set in seatunnel-web-env.sh"
    exit 1
fi

if [ -z "${SEATUNNEL_HOME}" ]; then
    echo "Error: SEATUNNEL_HOME is not set. It must be set in seatunnel-web-env.sh"
    exit 1
fi

# start
start() {
  cd "${SEATUNNEL_WEB_HOME}" || exit
  sh ./bin/seatunnel-backend-daemon.sh start
}
# Stop the Seatunnel application
stop() {
  cd "${SEATUNNEL_WEB_HOME}" || exit
  sh ./bin/seatunnel-backend-daemon.sh stop
}

# Check the status of the Seatunnel application
status() {
   cd "${SEATUNNEL_WEB_HOME}" || exit
   sh ./bin/seatunnel-backend-daemon.sh status
}

# main
case "$1" in
"start")
  start
  ;;
"stop")
  stop
  ;;
"status")
  status
  ;;
*)
  echo "Usage: seatunnel-web {start|stop|status}"
  exit 1
esac
